### ISSUE TITLE
2.7.8 removed Vue

### ISSUE THREAD

**Issue by Dav1dde** [webjars/vue#17]
A lot of files were removed in 2.7.8: ffb569f1c0ea77689de155e2206cfa8ecb5f557e

Now the webjar pretty much does not contain Vue anymore.

**Comment by jamesward** [comment]
This is due to the upstream release no longer containing what is needed:
https://github.com/vuejs/vue/tree/v2.7.8/dist

You will need to either get the upstream project to fix this, or use an NPM WebJar for this.
